[project]
name = "406-ch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "jinja2>=3.1.4",
  "minify-html>=0.15",
  "pygments>=2.18",
  "pyromark>=0.9.13",
  "rcssmin>=1.1.2",
]

[tool.ruff]
target-version = "py313"
fix = true
lint.extend-select = [ "B", "C4", "C90", "DJ", "E", "F", "FBT", "G", "I", "INT", "PIE", "SIM", "UP", "W", "YTT" ]
lint.extend-ignore = [
  "BLE001",
  "DTZ007",
  "DTZ011",
  # No line length errors
  "E501",
  # Named lambdas are good for line golfing
  "E731",
]
lint.isort.combine-as-imports = true
lint.isort.lines-after-imports = 2
lint.mccabe.max-complexity = 10

[tool.coverage]
run.branch = true
run.omit = [
  "*migrate*",
  "*migrations*",
  "*venv*",
]
report.show_missing = true
report.skip_covered = true
