# Generated by Django 1.11.2 on 2017-06-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("blog", "0003_auto_20160901_1627")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=200, unique=True, verbose_name="slug"),
        )
    ]
