# Generated by Django 2.1.1 on 2018-09-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_auto_20180924_0822"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="content",
            field=models.TextField(blank=True, verbose_name="content"),
        ),
        migrations.AddField(
            model_name="category",
            name="html",
            field=models.TextField(default="", editable=False, verbose_name="HTML"),
            preserve_default=False,
        ),
    ]
