# Generated by Django 3.1.1 on 2020-10-20 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_auto_20180924_0944"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="url_override",
        ),
    ]
