name: Pages
on:
  push:
    branches:
    - main
  schedule:
  - cron: 37 3 * * *
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        version: latest
        enable-cache: true
    - name: Build site
      run: uv run generate.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@1ef5a1b1df4c63fe21a2242edbee6cac921ece01 # v4.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./htdocs/
        cname: 406.ch
