name: Pages
on:
  push:
    branches:
    - main
  schedule:
  - cron: 37 3 * * *
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
        enable-cache: true
    - name: Build site
      run: uv run --python=python3.12 generate.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@47f197a2200bb9de68ba5f48fad1c088eb1c4a32 # v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./htdocs/
        cname: 406.ch
